name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assembleDebug && find app/build/outputs
    - name: Setup Debug Session
      uses: P3TERX/debugger-action@master
    - name: Upload apk
      uses: actions/upload-artifact@v1
      with:
        name: app-release.apk
        path: app/build/outputs/apk/debug/app-debug.apk
